apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: rhopp-240410
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhopp-240410 
  name: rhopp-240410
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rhopp-240410
    weight: 100 
